In [1]:
import pandas as pd
import numpy as ny

In [2]:
# read all 12 months' city bike trip data
df1 =  pd.read_csv("2016rawdata/201601.csv")
df2 =  pd.read_csv("2016rawdata/201602.csv")
df3 =  pd.read_csv("2016rawdata/201603.csv")
df4 =  pd.read_csv("2016rawdata/201604.csv")
df5 =  pd.read_csv("2016rawdata/201605.csv")
df6 =  pd.read_csv("2016rawdata/201606.csv")
df7 =  pd.read_csv("2016rawdata/201607.csv")
df8 =  pd.read_csv("2016rawdata/201608.csv")
df9 =  pd.read_csv("2016rawdata/201609.csv")
df10 =  pd.read_csv("2016rawdata/201610.csv")
df11 =  pd.read_csv("2016rawdata/201611.csv")
df12 =  pd.read_csv("2016rawdata/201612.csv")

In [4]:
# Concatenate all 12 months data
data2016 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12])
data2016

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,362,2016-01-01 00:02:52,2016-01-01 00:08:54,3186,Grove St PATH,40.719586,-74.043117,3209,Brunswick St,40.724176,-74.050656,24647,Subscriber,1964.0,2
1,200,2016-01-01 00:18:22,2016-01-01 00:21:42,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24605,Subscriber,1962.0,1
2,202,2016-01-01 00:18:25,2016-01-01 00:21:47,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24689,Subscriber,1962.0,2
3,248,2016-01-01 00:23:13,2016-01-01 00:27:21,3209,Brunswick St,40.724176,-74.050656,3203,Hamilton Park,40.727596,-74.044247,24693,Subscriber,1984.0,1
4,903,2016-01-01 01:03:20,2016-01-01 01:18:24,3195,Sip Ave,40.730743,-74.063784,3210,Pershing Field,40.742677,-74.051789,24573,Customer,NaN,0
5,883,2016-01-01 01:03:28,2016-01-01 01:18:11,3195,Sip Ave,40.730743,-74.063784,3210,Pershing Field,40.742677,-74.051789,24442,Customer,NaN,0
6,445,2016-01-01 01:07:45,2016-01-01 01:15:11,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,24510,Subscriber,1988.0,2
7,192,2016-01-01 01:18:51,2016-01-01 01:22:03,3211,Newark Ave,40.721525,-74.046305,3203,Hamilton Park,40.727596,-74.044247,24625,Subscriber,1980.0,1
8,409,2016-01-01 01:23:44,2016-01-01 01:30:34,3187,Warren St,40.721124,-74.038051,3214,Essex Light Rail,40.712774,-74.036486,24429,Subscriber,1990.0,1
9,285,2016-01-01 01:25:12,2016-01-01 01:29:57,3187,Warren St,40.721124,-74.038051,3214,Essex Light Rail,40.712774,-74.036486,24407,Subscriber,1988.0,2
10,206,2016-01-01 01:45:34,2016-01-01 01:49:00,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,24377,Subscriber,1993.0,1
11,251,2016-01-01 02:02:55,2016-01-01 02:07:06,3213,Van Vorst Park,40.718489,-74.047727,3209,Brunswick St,40.724176,-74.050656,24605,Subscriber,1976.0,1
12,292,2016-01-01 02:20:38,2016-01-01 02:25:30,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,24721,Subscriber,1992.0,1
13,175,2016-01-01 02:23:37,2016-01-01 02:26:32,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24601,Subscriber,1991.0,1
14,769,2016-01-01 02:28:58,2016-01-01 02:41:47,3193,Lincoln Park,40.724605,-74.078406,3211,Newark Ave,40.721525,-74.046305,24606,Subscriber,1968.0,1
15,384,2016-01-01 02:39:07,2016-01-01 02:45:32,3209,Brunswick St,40.724176,-74.050656,3213,Van Vorst Park,40.718489,-74.047727,24470,Subscriber,1975.0,2
16,364,2016-01-01 02:39:28,2016-01-01 02:45:33,3209,Brunswick St,40.724176,-74.050656,3213,Van Vorst Park,40.718489,-74.047727,24542,Subscriber,1976.0,1
17,326,2016-01-01 02:47:39,2016-01-01 02:53:05,3186,Grove St PATH,40.719586,-74.043117,3202,Newport PATH,40.727224,-74.033759,24716,Subscriber,1992.0,1
18,341,2016-01-01 02:53:35,2016-01-01 02:59:17,3186,Grove St PATH,40.719586,-74.043117,3202,Newport PATH,40.727224,-74.033759,24687,Subscriber,1982.0,1
19,634,2016-01-01 02:54:56,2016-01-01 03:05:30,3194,McGinley Square,40.725340,-74.067622,3209,Brunswick St,40.724176,-74.050656,24675,Subscriber,1981.0,1
20,331,2016-01-01 03:02:35,2016-01-01 03:08:06,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,24687,Subscriber,1982.0,1
21,550,2016-01-01 03:10:25,2016-01-01 03:19:36,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,24531,Subscriber,1986.0,1
22,988,2016-01-01 03:16:33,2016-01-01 03:33:02,3196,Riverview Park,40.744319,-74.043991,3209,Brunswick St,40.724176,-74.050656,24662,Customer,NaN,0
23,969,2016-01-01 03:16:34,2016-01-01 03:32:43,3196,Riverview Park,40.744319,-74.043991,3209,Brunswick St,40.724176,-74.050656,24563,Subscriber,1984.0,1
24,378,2016-01-01 03:17:01,2016-01-01 03:23:19,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,24450,Subscriber,1981.0,1
25,368,2016-01-01 03:17:13,2016-01-01 03:23:21,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,24627,Subscriber,1982.0,2
26,287,2016-01-01 03:43:03,2016-01-01 03:47:51,3202,Newport PATH,40.727224,-74.033759,3183,Exchange Place,40.716247,-74.033459,24471,Subscriber,1986.0,1
27,286,2016-01-01 03:51:30,2016-01-01 03:56:16,3214,Essex Light Rail,40.712774,-74.036486,3187,Warren St,40.721124,-74.038051,24407,Subscriber,1988.0,2
28,539,2016-01-01 04:12:06,2016-01-01 04:21:05,3195,Sip Ave,40.730743,-74.063784,3212,Christ Hospital,40.734786,-74.050444,24664,Subscriber,1966.0,2
29,340,2016-01-01 04:16:04,2016-01-01 04:21:45,3195,Sip Ave,40.730743,-74.063784,3193,Lincoln Park,40.724605,-74.078406,24493,Subscriber,1972.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812162,1534,2016-12-31 23:45:48,2017-01-01 00:11:22,3372,E 74 St & 1 Ave,40.768974,-73.954823,505,6 Ave & W 33 St,40.749013,-73.988484,25231,Subscriber,1962.0,1
812163,870,2016-12-31 23:46:35,2017-01-01 00:01:05,383,Greenwich Ave & Charles St,40.735238,-74.000271,383,Greenwich Ave & Charles St,40.735238,-74.000271,26764,Subscriber,1987.0,1
812164,191,2016-12-31 23:46:46,2016-12-31 23:49:58,3241,Monroe St & Tompkins Ave,40.686203,-73.944694,344,Monroe St & Bedford Ave,40.685144,-73.953809,19072,Subscriber,1984.0,1
812165,519,2016-12-31 23:46:50,2016-12-31 23:55:29,438,St Marks Pl & 1 Ave,40.727791,-73.985649,247,Perry St & Bleecker St,40.735354,-74.004831,24936,Subscriber,1962.0,1
812166,549722,2016-12-31 23:47:26,2017-01-07 08:29:28,322,Clinton St & Tillary St,40.696192,-73.991218,3411,Bond St & Bergen St,40.684967,-73.986208,14545,Subscriber,NaN,0
812167,346,2016-12-31 23:47:26,2016-12-31 23:53:12,322,Clinton St & Tillary St,40.696192,-73.991218,3411,Bond St & Bergen St,40.684967,-73.986208,16692,Subscriber,NaN,0
812168,197,2016-12-31 23:47:30,2016-12-31 23:50:48,3113,Greenpoint Ave & Manhattan Ave,40.730260,-73.953940,3117,Franklin St & Dupont St,40.735640,-73.958660,26972,Subscriber,1988.0,1
812169,1806,2016-12-31 23:48:29,2017-01-01 00:18:35,3311,Columbia St & Kane St,40.687632,-74.001626,3311,Columbia St & Kane St,40.687632,-74.001626,16738,Customer,NaN,0
812170,1768,2016-12-31 23:48:51,2017-01-01 00:18:20,2008,Little West St & 1 Pl,40.705693,-74.016777,2008,Little West St & 1 Pl,40.705693,-74.016777,16818,Customer,NaN,0
812171,1855,2016-12-31 23:48:49,2017-01-01 00:19:45,2008,Little West St & 1 Pl,40.705693,-74.016777,2008,Little West St & 1 Pl,40.705693,-74.016777,21258,Subscriber,1992.0,2
812172,419,2016-12-31 23:48:58,2016-12-31 23:55:57,491,E 24 St & Park Ave S,40.740964,-73.986022,236,St Marks Pl & 2 Ave,40.728419,-73.987140,14929,Subscriber,1992.0,1
812173,781,2016-12-31 23:49:22,2017-01-01 00:02:24,368,Carmine St & 6 Ave,40.730386,-74.002150,488,W 39 St & 9 Ave,40.756458,-73.993722,27178,Subscriber,1968.0,1
812174,88,2016-12-31 23:49:42,2016-12-31 23:51:10,3146,E 81 St & 3 Ave,40.775730,-73.956753,3147,E 85 St & 3 Ave,40.778012,-73.954071,27134,Subscriber,1974.0,1
812175,227,2016-12-31 23:50:23,2016-12-31 23:54:11,499,Broadway & W 60 St,40.769155,-73.981918,3164,Columbus Ave & W 72 St,40.777057,-73.978985,25196,Subscriber,1985.0,1
812176,1473,2016-12-31 23:50:39,2017-01-01 00:15:13,3134,3 Ave & E 62 St,40.763126,-73.965269,345,W 13 St & 6 Ave,40.736494,-73.997044,20153,Subscriber,1953.0,1
812177,316,2016-12-31 23:51:27,2016-12-31 23:56:43,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,438,St Marks Pl & 1 Ave,40.727791,-73.985649,26790,Subscriber,1958.0,1
812178,983,2016-12-31 23:51:29,2017-01-01 00:07:53,513,W 56 St & 10 Ave,40.768254,-73.988639,509,9 Ave & W 22 St,40.745497,-74.001971,17504,Subscriber,NaN,0
812179,275,2016-12-31 23:51:55,2016-12-31 23:56:31,539,Metropolitan Ave & Bedford Ave,40.715348,-73.960241,3091,Frost St & Meeker St,40.717640,-73.948820,24819,Subscriber,1991.0,2
812180,2182,2016-12-31 23:52:04,2017-01-01 00:28:26,3360,Amsterdam Ave & W 79 St,40.782939,-73.978652,3162,W 78 St & Broadway,40.783400,-73.980931,26842,Subscriber,1975.0,2
812181,128,2016-12-31 23:52:34,2016-12-31 23:54:42,3438,E 76 St & 3 Ave,40.772249,-73.958421,3372,E 74 St & 1 Ave,40.768974,-73.954823,23151,Subscriber,1965.0,1
812182,1126,2016-12-31 23:52:54,2017-01-01 00:11:41,312,Allen St & Stanton St,40.722055,-73.989111,312,Allen St & Stanton St,40.722055,-73.989111,23952,Subscriber,1997.0,1
812183,1089,2016-12-31 23:53:23,2017-01-01 00:11:33,3171,Amsterdam Ave & W 82 St,40.785247,-73.976673,3165,Central Park West & W 72 St,40.775794,-73.976206,16115,Subscriber,1969.0,1
812184,750,2016-12-31 23:53:28,2017-01-01 00:05:58,3113,Greenpoint Ave & Manhattan Ave,40.730260,-73.953940,3093,N 6 St & Bedford Ave,40.717452,-73.958509,24939,Subscriber,1983.0,1
812185,1258,2016-12-31 23:53:42,2017-01-01 00:14:41,334,W 20 St & 7 Ave,40.742388,-73.997262,488,W 39 St & 9 Ave,40.756458,-73.993722,26811,Subscriber,1988.0,1
812186,121,2016-12-31 23:55:50,2016-12-31 23:57:52,3236,W 42 St & Dyer Ave,40.758985,-73.993800,478,11 Ave & W 41 St,40.760301,-73.998842,25923,Subscriber,1987.0,1
812187,441,2016-12-31 23:56:15,2017-01-01 00:03:36,284,Greenwich Ave & 8 Ave,40.739017,-74.002638,336,Sullivan St & Washington Sq,40.730477,-73.999061,16185,Subscriber,1974.0,2
812188,1026,2016-12-31 23:56:19,2017-01-01 00:13:26,281,Grand Army Plaza & Central Park S,40.764397,-73.973715,3143,5 Ave & E 78 St,40.776829,-73.963888,18267,NaN,1983.0,1
812189,1747,2016-12-31 23:56:35,2017-01-01 00:25:43,3424,E 106 St & Lexington Ave,40.791976,-73.945993,3295,Central Park W & W 96 St,40.791270,-73.964839,19899,Subscriber,1970.0,2
812190,951,2016-12-31 23:59:31,2017-01-01 00:15:23,3158,W 63 St & Broadway,40.771639,-73.982614,3169,Riverside Dr & W 82 St,40.787209,-73.981281,16866,Subscriber,1961.0,1
812191,1322,2016-12-31 23:59:56,2017-01-01 00:21:58,3263,Cooper Square & E 7 St,40.729236,-73.990868,498,Broadway & W 32 St,40.748549,-73.988084,25793,Subscriber,1985.0,1

In [5]:
# export new csv file
data2016.to_csv('citibike_2016.csv')

In [8]:
# read Citi Bike Daily Ridership and Membership Data
a = pd.read_csv("2016rawdata/2016q1.csv")
b = pd.read_csv("2016rawdata/2016q2.csv")
c = pd.read_csv("2016rawdata/2016q3.csv")
d = pd.read_csv("2016rawdata/2016q4.csv")

In [10]:
# # Concatenate 4 quarters
data_membership_ride = pd.concat([a, b, c, d])
data_membership_ride

,24-Hour Passes Purchased (midnight to 11:59 pm),3-Day Passes Purchased (midnight to 11:59 pm),7-Day Passes Purchased (midnight to 11:59 pm),Cumulative trips (since launch):,Date,Miles traveled to date:,Miles traveled today (midnight to 11:59 pm),Total Annual Members (All Time),Trips over the past 24-hours (midnight to 11:59pm)
0,919,NaN,51.0,24371025,1/1/2016,44606414,24429,159362,11009
1,877,NaN,34.0,24385612,1/2/2016,44635507,29093,159403,14587
2,784,NaN,27.0,24401111,1/3/2016,44665123,29616,159459,15499
3,166,NaN,33.0,24420704,1/4/2016,44701295,36172,159502,19593
4,121,NaN,22.0,24438757,1/5/2016,44733344,32049,159534,18053
5,265,NaN,27.0,24463326,1/6/2016,44774340,40996,159564,24569
6,318,NaN,24.0,24491099,1/7/2016,44820326,45986,159588,27773
7,364,NaN,28.0,24519808,1/8/2016,44867387,47061,159621,28709
8,632,NaN,20.0,24540654,1/9/2016,44904728,37341,159654,20846
9,391,NaN,18.0,24554929,1/10/2016,44930132,25404,159682,14275
10,155,NaN,32.0,24577866,1/11/2016,44967525,37393,159731,22937
11,151,NaN,23.0,24603077,1/12/2016,45006483,38958,159761,25211
12,82,NaN,15.0,24624210,1/13/2016,45038091,31608,159792,21133
13,123,NaN,29.0,24647990,1/14/2016,45075386,37295,159813,23780
14,379,NaN,27.0,24676425,1/15/2016,45121379,45993,159841,28435
15,803,NaN,37.0,24695603,1/16/2016,45157170,35791,159885,19178
16,387,NaN,22.0,24707627,1/17/2016,45177657,20487,159910,12024
17,123,NaN,13.0,24720345,1/18/2016,45197655,19998,159931,12718
18,64,NaN,12.0,24737626,1/19/2016,45224621,26966,159957,17281
19,126,NaN,11.0,24761045,1/20/2016,45260098,35477,159972,23419
20,133,NaN,15.0,24784716,1/21/2016,45296146,36048,159991,23671
21,115,NaN,6.0,24805666,1/22/2016,45327490,31344,160004,20950
22,0,NaN,0.0,24805666,1/23/2016,45327490,0,160005,0
23,0,NaN,0.0,24805666,1/24/2016,45327490,0,160013,0
24,0,NaN,0.0,24805666,1/25/2016,45327490,0,160020,0
25,0,NaN,0.0,24805666,1/26/2016,45327490,0,160028,0
26,54,NaN,6.0,24812426,1/27/2016,45341188,13698,160039,6760
27,81,NaN,9.0,24824370,1/28/2016,45363502,22314,160053,11944
28,118,NaN,27.0,24840398,1/29/2016,45390398,26896,160064,16028
29,328,NaN,23.0,24853362,1/30/2016,45413748,23350,160084,12964
...,...,...,...,...,...,...,...,...,...
62,440,52.0,NaN,\t37475411,12/2/2016,\t73422008,89092,205794,42358
63,854,58.0,NaN,\t37505264,12/3/2016,\t73492861,70853,205824,29853
64,930,28.0,NaN,\t37532718,12/4/2016,\t73564590,71729,205857,27454
65,278,38.0,NaN,\t37568645,12/5/2016,\t73644804,80214,205897,35927
66,228,26.0,NaN,\t37601970,12/6/2016,\t73711991,67187,205939,33325
67,270,18.0,NaN,\t37639980,12/7/2016,\t73788596,76605,205967,38010
68,235,23.0,NaN,\t37679601,12/8/2016,\t73860815,72219,205998,39621
69,214,31.0,NaN,\t37713141,12/9/2016,\t73924765,63950,206021,33540
70,490,20.0,NaN,37735520,12/10/2016,73977481,52716,206033,22379
71,287,6.0,NaN,\t37753318,12/11/2016,\t74019221,41740,206049,17798
72,175,14.0,NaN,\t37782353,12/12/2016,\t74077922,58701,206066,29035
73,299,21.0,NaN,\t37821376,12/13/2016,\t74146780,68858,206090,39023
74,257,16.0,NaN,\t37859175,12/14/2016,\t74218578,71798,206130,37799
75,80,13.0,NaN,\t37884177,12/15/2016,\t74264418,45840,206145,25002
76,139,11.0,NaN,\t37908661,12/16/16,\t74312706,48288,206171,24484
77,36,7.0,NaN,\t37915654,12/17/16,\t74335069,22363,206176,6993
78,168,14.0,NaN,\t37931949,12/18/16,\t74373528,38459,206200,16295
79,119,12.0,NaN,\t37957597,12/19/16,\t74423933,50405,206225,25648
80,202,22.0,NaN,\t37985274,12/20/16,\t74474341,50408,206250,27677
81,244,20.0,NaN,\t38015885,12/21/16,\t74530087,55746,206270,30611
82,302,18.0,NaN,\t38046759,12/22/16,\t74586528,56441,206293,30874
83,399,27.0,NaN,\t38073094,12/23/16,\t74639846,53318,206320,26335
84,147,10.0,NaN,38081108,12/24/16,\t74667879,28033,206334,8014
85,1052,43.0,NaN,38091027,12/25/16,\t74706088,38209,206369,9919
86,315,27.0,NaN,\t38101801,12/26/16,\t74738534,32446,206400,10774
87,960,68.0,NaN,\t38127747,12/27/16,\t74799913,61379,206450,25946
88,619,38.0,NaN,\t38151343,12/28/16,\t74852850,52937,206476,23596
89,104,8.0,NaN,\t38164545,12/29/16,\t74882481,29631,206503,13202
90,641,49.0,NaN,\t38185911,12/30/16,\t74928224,45743,206543,21366
91,798,33.0,NaN,\t38201836,12/31/16,\t74975034,46810,206585,15925

In [11]:
# export new csv file
data_membership_ride.to_csv('Ridership_Membership_Data.csv')